import type { DataLayerConfig } from '../types';

export const DATA_LAYERS: DataLayerConfig[] = [
  {
    id: 'wind-potential',
    name: 'Wind Potential Zones',
    description: 'High-yield wind resource areas identified by Princeton NZA Optimal Renewable Buildout',
    color: '#7c3aed',
    type: 'fill',
    sourceUrl: '/data/layers/wind-potential.geojson',
    opacity: 0.35,
    attribution: 'Princeton NZA (illustrative)',
  },
  {
    id: 'solar-irradiance',
    name: 'Solar Irradiance',
    description: 'High-irradiance zones suitable for utility-scale solar development',
    color: '#f59e0b',
    type: 'fill',
    sourceUrl: '/data/layers/solar-irradiance.geojson',
    opacity: 0.35,
    attribution: 'Princeton NZA (illustrative)',
  },
  {
    id: 'co2-storage',
    name: 'CO₂ Storage Formations',
    description: 'Saline aquifers and depleted reservoirs for geologic carbon sequestration',
    color: '#0d9488',
    type: 'fill',
    sourceUrl: '/data/layers/co2-storage.geojson',
    opacity: 0.4,
    attribution: 'Princeton NZA (illustrative)',
  },
  {
    id: 'tx-corridors-2030',
    name: 'Transmission Corridors 2030',
    description: 'Projected high-voltage transmission expansion paths by 2030',
    color: '#f97316',
    type: 'line',
    sourceUrl: '/data/layers/tx-corridors-2030.geojson',
    opacity: 0.8,
    attribution: 'REPEAT Project (illustrative)',
  },
  {
    id: 'tx-corridors-2050',
    name: 'Transmission Corridors 2050',
    description: 'Long-range transmission buildout corridors for 2050 net-zero scenarios',
    color: '#ef4444',
    type: 'line',
    sourceUrl: '/data/layers/tx-corridors-2050.geojson',
    opacity: 0.7,
    attribution: 'REPEAT Project (illustrative)',
  },
  {
    id: 'constrained-land',
    name: 'Constrained Land (CLUA)',
    description: 'Protected areas, ecological constraints, and no-go zones per Princeton CLUA assumptions',
    color: '#6b7280',
    type: 'fill',
    sourceUrl: '/data/layers/constrained-land.geojson',
    opacity: 0.3,
    attribution: 'Princeton NZA CLUA (illustrative)',
  },
];
